/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    ServerStats: () => import('#controllers/admin/server_stats_controller'),
  },
  DevRoutes: () => import('#controllers/dev_routes_controller'),
  EnhancedAuth: () => import('#controllers/enhanced_auth_controller'),
  EnhancedLobbies: () => import('#controllers/enhanced_lobbies_controller'),
  Games: () => import('#controllers/games_controller'),
  Lobbies: () => import('#controllers/lobbies_controller'),
  SimpleLobbies: () => import('#controllers/simple_lobbies_controller'),
  support: {
    GameControllerGuard: () => import('#controllers/support/game_controller_guard'),
  },
}
