/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  DevRoutes: () => import('#controllers/dev_routes_controller'),
  EnhancedAuth: () => import('#controllers/enhanced_auth_controller'),
  EnhancedLobbies: () => import('#controllers/enhanced_lobbies_controller'),
  FriendPresence: () => import('#controllers/friend_presence_controller'),
  Friends: () => import('#controllers/friends_controller'),
  GameCatalog: () => import('#controllers/game_catalog_controller'),
  Games: () => import('#controllers/games_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  ProfileSettings: () => import('#controllers/profile_settings_controller'),
  support: {
    EnhancedLobbiesControllerActions: () => import('#controllers/support/enhanced_lobbies_controller_actions'),
    EnhancedLobbiesControllerJoin: () => import('#controllers/support/enhanced_lobbies_controller_join'),
    EnhancedLobbiesControllerPresence: () => import('#controllers/support/enhanced_lobbies_controller_presence'),
    EnhancedLobbiesControllerResponse: () => import('#controllers/support/enhanced_lobbies_controller_response'),
    EnhancedLobbiesControllerSuccess: () => import('#controllers/support/enhanced_lobbies_controller_success'),
    GameControllerGuard: () => import('#controllers/support/game_controller_guard'),
    GameControllerPersistence: () => import('#controllers/support/game_controller_persistence'),
    GameControllerReplayAdmin: () => import('#controllers/support/game_controller_replay_admin'),
    GameControllerRuntimeApi: () => import('#controllers/support/game_controller_runtime_api'),
    GameControllerRuntime: () => import('#controllers/support/game_controller_runtime'),
  },
}
