/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/drive.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/i18n.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/server_stats.ts" />
/// <reference path="../../config/transmit.ts" />
