/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GameSchema extends BaseModel {
  static $columns = ['createdAt', 'durationMs', 'finishedAt', 'gameData', 'isArchived', 'players', 'startedAt', 'status', 'updatedAt', 'uuid', 'winnerUuid'] as const
  $columns = GameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare gameData: any
  @column()
  declare isArchived: boolean
  @column()
  declare players: any
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare uuid: string | null
  @column()
  declare winnerUuid: string | null
}

export class LobbySchema extends BaseModel {
  static $columns = ['availableActions', 'createdAt', 'createdBy', 'deletedAt', 'description', 'gameSettings', 'gameType', 'id', 'isPrivate', 'maxPlayers', 'name', 'passwordHash', 'status', 'updatedAt', 'uuid'] as const
  $columns = LobbySchema.$columns
  @column()
  declare availableActions: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare gameSettings: string
  @column()
  declare gameType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrivate: boolean | null
  @column()
  declare maxPlayers: number
  @column()
  declare name: string
  @column()
  declare passwordHash: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class LobbyPlayerSchema extends BaseModel {
  static $columns = ['createdAt', 'joinedAt', 'lobbyId', 'updatedAt', 'userId', 'uuid'] as const
  $columns = LobbyPlayerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare lobbyId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
  @column({ isPrimary: true })
  declare uuid: string | null
}

export class PlayerSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'deletedAt', 'id', 'nickName', 'playerUuid', 'updatedAt', 'userUuid'] as const
  $columns = PlayerSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nickName: string
  @column()
  declare playerUuid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt', 'userUuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
}
