/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class GameSchema extends BaseModel {
  static $columns = ['uuid', 'status', 'players', 'gameData', 'winnerUuid', 'startedAt', 'finishedAt', 'durationMs', 'isArchived', 'createdAt', 'updatedAt'] as const
  $columns = GameSchema.$columns
  @column()
  declare uuid: string | null
  @column()
  declare status: string
  @column()
  declare players: any
  @column()
  declare gameData: any
  @column()
  declare winnerUuid: string | null
  @column.dateTime()
  declare startedAt: DateTime
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare durationMs: number | null
  @column()
  declare isArchived: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LobbySchema extends BaseModel {
  static $columns = ['id', 'uuid', 'name', 'maxPlayers', 'isPrivate', 'status', 'createdBy', 'availableActions', 'deletedAt', 'createdAt', 'updatedAt', 'gameType', 'gameSettings'] as const
  $columns = LobbySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare uuid: string
  @column()
  declare name: string
  @column()
  declare maxPlayers: number
  @column()
  declare isPrivate: boolean | null
  @column()
  declare status: string
  @column()
  declare createdBy: string
  @column()
  declare availableActions: any | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare gameType: string
  @column()
  declare gameSettings: string
}

export class LobbyPlayerSchema extends BaseModel {
  static $columns = ['uuid', 'lobbyId', 'userId', 'joinedAt', 'createdAt', 'updatedAt'] as const
  $columns = LobbyPlayerSchema.$columns
  @column()
  declare uuid: string | null
  @column()
  declare lobbyId: number
  @column()
  declare userId: number
  @column.dateTime()
  declare joinedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PlayerSchema extends BaseModel {
  static $columns = ['id', 'playerUuid', 'userUuid', 'nickName', 'avatarUrl', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = PlayerSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare playerUuid: string
  @column()
  declare userUuid: string
  @column()
  declare nickName: string
  @column()
  declare avatarUrl: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'userUuid', 'fullName', 'email', 'password', 'deletedAt', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userUuid: string
  @column()
  declare fullName: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
