/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class FriendRequestSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'pairKey', 'recipientUserUuid', 'requesterUserUuid', 'respondedAt', 'status', 'updatedAt', 'uuid'] as const
  $columns = FriendRequestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pairKey: string
  @column()
  declare recipientUserUuid: string
  @column()
  declare requesterUserUuid: string
  @column.dateTime()
  declare respondedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class FriendshipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'pairKey', 'updatedAt', 'userAUuid', 'userBUuid', 'uuid'] as const
  $columns = FriendshipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pairKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAUuid: string
  @column()
  declare userBUuid: string
  @column()
  declare uuid: string
}

export class GameSchema extends BaseModel {
  static $columns = ['createdAt', 'durationMs', 'finishedAt', 'gameData', 'isArchived', 'players', 'startedAt', 'status', 'updatedAt', 'uuid', 'winnerUuid'] as const
  $columns = GameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare durationMs: number | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column()
  declare gameData: any
  @column()
  declare isArchived: boolean
  @column()
  declare players: any
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column({ isPrimary: true })
  declare uuid: string | null
  @column()
  declare winnerUuid: string | null
}

export class InvitationCodeSchema extends BaseModel {
  static $columns = ['codeDigest', 'createdAt', 'expiresAt', 'id', 'issuerUserUuid', 'maxUses', 'restrictedEmail', 'revokedAt', 'status', 'updatedAt', 'usedAt', 'usedByUserUuid', 'usedCount', 'uuid'] as const
  $columns = InvitationCodeSchema.$columns
  @column()
  declare codeDigest: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare issuerUserUuid: string
  @column()
  declare maxUses: number
  @column()
  declare restrictedEmail: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare usedByUserUuid: string | null
  @column()
  declare usedCount: number
  @column()
  declare uuid: string
}

export class InvitationRateLimitSchema extends BaseModel {
  static $columns = ['attemptCount', 'blockedUntilMs', 'createdAt', 'firstAttemptAtMs', 'identifier', 'updatedAt'] as const
  $columns = InvitationRateLimitSchema.$columns
  @column()
  declare attemptCount: number
  @column()
  declare blockedUntilMs: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstAttemptAtMs: bigint | number
  @column({ isPrimary: true })
  declare identifier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LobbySchema extends BaseModel {
  static $columns = ['availableActions', 'createdAt', 'createdBy', 'deletedAt', 'description', 'gameSettings', 'gameType', 'id', 'isPrivate', 'maxPlayers', 'name', 'passwordHash', 'status', 'updatedAt', 'uuid'] as const
  $columns = LobbySchema.$columns
  @column()
  declare availableActions: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare gameSettings: string
  @column()
  declare gameType: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPrivate: boolean | null
  @column()
  declare maxPlayers: number
  @column()
  declare name: string
  @column()
  declare passwordHash: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare uuid: string
}

export class LobbyPlayerSchema extends BaseModel {
  static $columns = ['createdAt', 'joinedAt', 'lobbyId', 'updatedAt', 'userId', 'uuid'] as const
  $columns = LobbyPlayerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare joinedAt: DateTime
  @column()
  declare lobbyId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
  @column({ isPrimary: true })
  declare uuid: string | null
}

export class LoginRateLimitSchema extends BaseModel {
  static $columns = ['attemptCount', 'blockedUntilMs', 'createdAt', 'firstAttemptAtMs', 'identifier', 'updatedAt'] as const
  $columns = LoginRateLimitSchema.$columns
  @column()
  declare attemptCount: number
  @column()
  declare blockedUntilMs: bigint | number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare firstAttemptAtMs: bigint | number
  @column({ isPrimary: true })
  declare identifier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlayerSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'deletedAt', 'id', 'nickName', 'playerUuid', 'updatedAt', 'userUuid'] as const
  $columns = PlayerSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nickName: string
  @column()
  declare playerUuid: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
}

export class ReplayVerificationAuditSchema extends BaseModel {
  static $columns = ['accepted', 'actorId', 'createdAt', 'envelopeAlgorithm', 'envelopeKeyId', 'envelopeSignedAt', 'id', 'metadata', 'operation', 'reason', 'source', 'targetId'] as const
  $columns = ReplayVerificationAuditSchema.$columns
  @column()
  declare accepted: boolean
  @column()
  declare actorId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare envelopeAlgorithm: string | null
  @column()
  declare envelopeKeyId: string | null
  @column()
  declare envelopeSignedAt: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare operation: string
  @column()
  declare reason: string | null
  @column()
  declare source: string
  @column()
  declare targetId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'fullName', 'id', 'invitedByUserUuid', 'password', 'role', 'updatedAt', 'userUuid'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invitedByUserUuid: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userUuid: string
}
